### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bounlu** [leekgroup/regionReport#10]
Hi,

When running `regionReport` with the `DESeq2Report` function, I get the below error:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to data.crossref.org port 80: No route to host
```

I think it's something related to the proxy or unavailability of the server.

Although the error seems to come from the dependency package `curl`, is there a way to fix or bypass this in `regionReport`?

How?

**Comment by lcolladotor** [comment]
Hi @bounlu,

Could you provide a small reproducible example please as well as your R session information? Thanks!

It could be that port 80 is blocked in the wifi you are using, so maybe trying with a different internet connection will help. 

Best,
Leonardo

**Comment by bounlu** [comment]
It sometimes works sometimes does not. I am connected via a fixed ip on the server.

`> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1`

**Comment by lcolladotor** [comment]
How did you create those objects? I was looking for something that I can run and see the error myself to try to debug. If you want to, subset those objects or prepare some random data where you also see the error and send it to me via email.

Best,
Leonardo

**Comment by lcolladotor** [comment]
I'm closing this issue since we haven't heard back from the issue author.
